### ISSUE TITLE
Unable to reserve cache with key X another job may be creating this cache

### ISSUE THREAD

**Issue by ruudk** [shivammathur/cache-extensions#22]
**Describe the bug**
Since today our workflows started failing 80% of the time. 

**Version**
- Latest version

**Runners**

- GitHub Hosted

**Operating systems**
* Ubuntu 20.04

**PHP versions**
* 8.0

**To Reproduce**
```
env:
    REQUIRED_PHP_TOOLS: cs2pr
    REQUIRED_PHP_EXTENSIONS: mbstring,bcmath,intl,gd,zip,memcached,redis,rdkafka
    PHP_VERSION: '8.0'
jobs:
    checks-and-guards:
        strategy:
            fail-fast: false
        runs-on: ubuntu-20.04
        steps:
            -   name: Checkout
                uses: actions/checkout@v2.4.0
                with:
                    ref: ${{ github.event.pull_request.head.sha }}
                    fetch-depth: 0
            -   name: Setup cache environment
                id: extcache
                uses: shivammathur/cache-extensions@1.6.2
                with:
                    php-version: ${{ env.PHP_VERSION }}
                    extensions: ${{ env.REQUIRED_PHP_EXTENSIONS }}
                    key: php-build-v1
```
**Expected behavior**
No error

**Additional context**
Feels like a race condition similar to https://github.com/ramsey/composer-install/pull/195
