### ISSUE TITLE
Error: getCacheEntry failed: Cache service responded with 503

### ISSUE THREAD

**Issue by Jeckerson** [shivammathur/cache-extensions#25]
**Describe the bug**

**Version**
- [x] I have checked releases and the bug exists in the latest patch version of `v1`.
- [ ] `v2`
- [x] `v1`

**Runners**

- [x] GitHub Hosted
- [ ] Self Hosted

**Operating systems**

**PHP versions**
7.4

**To Reproduce**
```
- name: Setup PHP Cache Environment
        id: cache-ext
        uses: shivammathur/cache-extensions@v1
        with:
          php-version: '7.4'
          extensions: mbstring, intl, json, psr, phalcon4, pcov
          key: cache-v4
```
