### ISSUE TITLE
'Operation not permitted' cache-extension is not working.

### ISSUE THREAD

**Issue by youngjin-yun-kurly** [shivammathur/cache-extensions#27]
**Describe the bug**

**Version**
- [ ] I have checked releases and the bug exists in the latest patch version of `v1`.
- [x] `v2`
- [ ] `v1`

**Runners**

- [ ] GitHub Hosted
- [x] Self Hosted

**Operating systems**

ubuntu-latest

**PHP versions**

8.1

**To Reproduce**

```yml
  testing:
    runs-on: self-hosted
    env:
      php-version: '7.4'
      extensions: rdkafka-arnaud-lb/php-rdkafka@4.0.3, apcu, bcmath, gd, redis-phpredis/phpredis@5.3.5, sqlite, pdo_sqlite, igbinary
      key: cache-20220830
    steps:
      - name: Setup cache environment
        id: extcache
        uses: shivammathur/cache-extensions@v1
        with:
          php-version: ${{ env.php-version }}
          extensions: ${{ env.extensions }}
          key: ${{ env.key }}
      - name: Cache extensions
        uses: actions/cache@v2
        with:
          path: ${{ steps.extcache.outputs.dir }}
          key: ${{ steps.extcache.outputs.key }}
          restore-keys: ${{ steps.extcache.outputs.key }}
      - name: Setup PHP with tools
        uses: shivammathur/setup-php@v2
        env:
          RDKAFKA_LIBS: librdkafka-dev
        with:
          php-version: ${{ env.php-version }}
          extensions: ${{ env.extensions }}
```

**Expected behavior**

```
Cache Size: ~4 MB (3871195 B)
/usr/bin/tar -z -xf /opt/actions-runner/_work/_temp/1e76a422-1264-4a39-ac63-d15b40879d26/cache.tgz -P -C /opt/actions-runner/_work/some-project/some-project
/usr/bin/tar: ../../../../../usr/lib/php/20190902/deps: Cannot utime: Operation not permitted
/usr/bin/tar: ../../../../../usr/lib/php/20190902/calendar.so: Cannot open: Permission denied
/usr/bin/tar: ../../../../../usr/lib/php/20190902/ctype.so: Cannot open: Permission denied
/usr/bin/tar: ../../../../../usr/lib/php/20[19](https://github.com/thefarmersfront/kurly-laravel-boilerplate/runs/8085934635?check_suite_focus=true#step:4:20)0902/exif.so: Cannot open: Permission denied
/usr/bin/tar: ../../../../../usr/lib/php/[20](https://github.com/thefarmersfront/kurly-laravel-boilerplate/runs/8085934635?check_suite_focus=true#step:4:21)190902/ffi.so: Cannot open: Permission denied
/usr/bin/tar: ../../../../../usr/lib/php/20190902/fileinfo.so: Cannot open: Permission denied
/usr/bin/tar: ../../../../../usr/lib/php/20190902/ftp.so: Cannot open: Permission denied
/usr/bin/tar: ../../../../../usr/lib/php/20190902/gettext.so: Cannot open: Permission denied
/usr/bin/tar: ../../../../../usr/lib/php/20190902/iconv.so: Cannot open: Permission denied
/usr/bin/tar: ../../../../../usr/lib/php/20190902/pdo.so: Cannot open: Permission denied
/usr/bin/tar: ../../../../../usr/lib/php/20190902/phar.so: Cannot open: Permission denied
/usr/bin/tar: ../../../../../usr/lib/php/20190902/posix.so: Cannot open: Permission denied
/usr/bin/tar: ../../../../../usr/lib/php/20190902/shmop.so: Cannot open: Permission denied
/usr/bin/tar: ../../../../../usr/lib/php/20190902/sockets.so: Cannot open: Permission denied
...
/usr/bin/tar: Exiting with failure status due to previous errors
Warning: Tar failed with error: The process '/usr/bin/tar' failed with exit code 2
```

**Screenshots/Logs**

**Additional context**

cache is not working.

**Are you willing to submit a PR?**
