### ISSUE TITLE
PHP Cache

### ISSUE THREAD

**Issue by benblub** [shivammathur/cache-extensions#28]
**Describe the bug**

This needs around 1 second with or without cache 
````yaml
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        extensions: mbstring, xml, ctype, iconv, intl, pdo_sqlite, imagick, amqp
        coverage: pcov
````

This needs around 1 minute 30 second with or without cache 
```yaml
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        extensions: pcntl-php/php-src@PHP-8.1, mbstring, xml, ctype, iconv, intl, pdo_sqlite, imagick, amqp
        coverage: pcov
        ini-values: sendmail_path=/usr/local/bin/mhsendmail
      env:
        PCNTL_PATH: ext/pcntl
        PCNTL_CONFIGURE_OPTS: '--enable-pcntl'
```

**Version**
- [ ] I have checked releases and the bug exists in the latest patch version of `v1`.
- [x] `v2`
- [ ] `v1`

**Runners**
- [x] GitHub Hosted

**Operating systems**
Ubuntu-latest

**PHP versions**
8.1

**To Reproduce**

**Expected behavior**
save build time

**Screenshots/Logs**
Use without cache and some common extensions needs 1 second
![Bildschirmfoto 2022-09-28 um 11 29 45](https://user-images.githubusercontent.com/1756031/192743907-f7fcc3a6-dd7a-4d3a-8a55-6ebfc826c26a.png)

![Bildschirmfoto 2022-09-28 um 11 29 45](https://user-images.githubusercontent.com/1756031/192745001-4dcaf764-95a8-485b-a383-c0b64dc18879.png)

![Bildschirmfoto 2022-09-28 um 11 35 18](https://user-images.githubusercontent.com/1756031/192745044-02a5fee7-0b24-4de7-8981-92520c3e6a04.png)
