### ISSUE TITLE
self-hosted (?) Failed to setup libaio-dev

### ISSUE THREAD

**Issue by MarcHagen** [shivammathur/cache-extensions#32]
**Describe the bug**
```
==> Setup libraries
Logs to set up required libraries
  Reading package lists...
  Building dependency tree...
  Reading state information...
  E: Unable to locate package libaio-dev
✗ libaio-dev Failed to setup libaio-dev
```

**Version**
- [x] I have checked releases and the bug exists in the latest patch version of `v1`.
- [ ] `v2`
- [ ] `v1`

**Runners**

- [ ] GitHub Hosted
- [x] Self Hosted

**Operating systems**
`summerwind/actions-runner-dind:ubuntu-22.04`

**PHP versions**
8.1, 8.2, 8.3

**To Reproduce**
```
jobs:
  run:
    name: PHP ${{ matrix.php-versions }} Test on ${{ matrix.operating-system }}
    runs-on: ${{ matrix.operating-system }}
    env:
      APP_ENV: github
      PHP_CS_FIXER_IGNORE_ENV: 1
      extensions: mbstring, pdo, pdo_mysql, intl, zip
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ self-hosted ]
        php-versions: [ 8.1, 8.2, 8.3 ]

    continue-on-error: ${{ matrix.php-versions == 8.3 }}

    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Setup cache environment
        id: extcache
        uses: shivammathur/cache-extensions@f6bffb2308b2a322d68fac3610257ad04ca32fe4 # pin @1.9.1
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: ${{ env.extensions }}
          key: ${{ runner.os }}-setup-php-
        env:
          runner: self-hosted
      -
        name: Cache extensions
        uses: actions/cache@v3
        with:
          path: ${{ steps.extcache.outputs.dir }}
          key: ${{ steps.extcache.outputs.key }}${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ steps.extcache.outputs.key }}
      -
        name: Setup PHP
        uses: shivammathur/setup-php@c5fc0d8281aba02c7fda07d3a70cc5371548067d # pin @v2
        with:
          ini-values: >-
            variables_order=EGPCS
          php-version: ${{ matrix.php-versions }}
          extensions: ${{ env.extensions }}
        env:
          runner: self-hosted
```

**Expected behavior**
Working cache same as `shivammathur/setup-php`

**Screenshots/Logs**

**Additional context**

**Are you willing to submit a PR?**
