### ISSUE TITLE
Cache not found

### ISSUE THREAD

**Issue by B0bbyD0llar** [shivammathur/cache-extensions#45]
**Describe the bug**

The process appears to run smoothly. The network load suggests that quite a bit of data is being loaded. The output in the step indicates that the data was correctly stored in the cache. However, in the next step, it shows that the cache could not be found. Additionally, setting up PHP takes just as long as when no cache is configured.

**Version**
- [X] I have checked releases and the bug exists in the latest patch version of `v1`.
- [ ] `v2`
- [ ] `v1`

**Runners**
- [ ] GitHub Hosted
- [X] Self Hosted

**Operating systems**
ubuntu-latest (Ubuntu 2404)

**PHP versions**
8.2

**To Reproduce**
```yaml
    strategy:
      matrix:
        php-version:
          - "8.2"
    env:
      extensions: apcu, calendar, ctype, curl, ds, dom, fileinfo, filter, iconv, intl, json, ldap, mbstring, mysqlnd, pdo, pdo_mysql, pdo_sqlite
      key: "cache-v6"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4.2.2"
      - name: "Setup php extensions cache environment"
        id: extcache
        uses: "shivammathur/cache-extensions@1.11.1"
        with:
          php-version: "${{ matrix.php-version }}"
          extensions: "${{ env.extensions }}"
          key: "${{ env.key }}"
      - name: "Show key information"
        run: |
          echo ${{ env.key }}
          echo ${{ steps.extcache.outputs.dir }}
          echo ${{ steps.extcache.outputs.key }}
      - name: "Cache php extensions"
        uses: "actions/cache@v4.1.2"
        with:
          path: "${{ steps.extcache.outputs.dir }}"
          key: "${{ steps.extcache.outputs.key }}"
          restore-keys: "${{ steps.extcache.outputs.key }}"
      - name: "Set up PHP"
        uses: "shivammathur/setup-php@2.31.1"
        with:
          coverage: "none"
          extensions:  apcu, calendar, ctype, curl, ds, dom, fileinfo, filter, gd, iconv, imap, intl, json, ldap, mbstring, mysqlnd, pdo, pdo_mysql, pdo_sqlite, redis, session, simplexml, tokenizer, xml, xmlreader, xmlwriter, zip, zlib
          php-version: ${{ matrix.php-version }}
        env:
          runner: self-hosted
```

**Expected behavior**

Cache size should not be ~0MB, and the cache should be found. Also, the setup-PHP step should run faster than when there are no cached extensions.

**Screenshots/Logs**
+ Setup php extensions cache environment
```bash
[command]/usr/bin/bash /run/act/actions/a4b689274cdadbd8b09084a274a674cb98a23347f69380f3fc6befa4369e5bac/src/scripts/cache.sh data apcu, calendar, ctype, curl, ds, dom, fileinfo, filter, iconv, intl, json, ldap, mbstring, mysqlnd, pdo, pdo_mysql, pdo_sqlite 8.2 cache-v6
[command]/usr/bin/bash /run/act/actions/a4b68974cdadbd8b09084a274a674cb98a23347f69380f3fc6befa4369e5bac/src/scripts/cache.sh dependencies apcu, calendar, ctype, curl, ds, dom, fileinfo, filter, iconv, intl, json, ldap, mbstring, mysqlnd, pdo, pdo_mysql, pdo_sqlite 8.2
==> Setup libraries
::group::Logs to set up required libraries
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package libaio-dev
Get:1 http://security.ubuntu.com/ubuntu jammy-security InRelease [129 kB]
Get:2 https://packages.microsoft.com/ubuntu/22.04/prod jammy InRelease [632 B]
Get:3 http://archive.ubuntu.com/ubuntu jammy InRelease [270 kB]
Get:4 https://ppa.launchpadcontent.net/git-core/ppa/ubuntu jammy InRelease [24.6 kB]
Get:5 http://security.ubuntu.com/ubuntu jammy-security/universe amd64 Packages [1163 kB]
Get:6 https://packages.microsoft.com/ubuntu/22.04/prod jammy/main amd64 Packages [10 kB]
Get:7 https://ppa.launchpadcontent.net/git-core/ppa/ubuntu jammy/main amd64 Packages [2959 B]
Get:8 http://security.ubuntu.com/ubuntu jammy-security/multiverse amd64 Packages [44.7 kB]
Get:9 http://security.ubuntu.com/ubuntu jammy-security/restricted amd64 Packages [3241 kB]
Get:10 https://packages.microsoft.com/ubuntu/22.04/prod jammy/main all Packages [1243 B]
Get:11 http://security.ubuntu.com/ubuntu jammy-security/main amd64 Packages [2397 kB]
Get:12 http://archive.ubuntu.com/ubuntu jammy-updates InRelease [128 kB]
Get:13 http://archive.ubuntu.com/ubuntu jammy-backports InRelease [127 kB]
Get:14 http://archive.ubuntu.com/ubuntu jammy/restricted amd64 Packages [164 kB]
Get:15 http://archive.ubuntu.com/ubuntu jammy/multiverse amd64 Packages [266 kB]
Get:16 http://archive.ubuntu.com/ubuntu jammy/main amd64 Packages [1792 kB]
Get:17 http://archive.ubuntu.com/ubuntu jammy/universe amd64 Packages [17.5 MB]
Get:19 http://archive.ubuntu.com/ubuntu jammy-updates/restricted amd64 Packages [3319 kB]
Get:20 http://archive.ubuntu.com/ubuntu jammy-updates/universe amd64 Packages [52 kB]
Get:21 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 Packages [2672 kB]
Get:22 http://archive.ubuntu.com/ubuntu jammy-updates/multiverse amd64 Packages [51.8 kB]
Get:23 http://archive.ubuntu.com/ubuntu jammy-backports/universe amd64 Packages [33.7 kB]
Get:24 http://archive.ubuntu.com/ubuntu jammy-backports/main amd64 Packages [81.4 kB]
Get:18 https://packagecloud.io/github/git-lfs/ubuntu jammy InRelease [28.0 kB]
Get:25 https://packagecloud.io/github/git-lfs/ubuntu jammy/main amd64 Packages [1842 B]
Fetched 35.0 MB in 8s (4252 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
Skipping libicu70, it is already installed and upgrade is not set.
libicu70 set to manually installed.
Skipping libonig5, it is already installed and upgrade is not set.
libonig5 set to manually installed.
Skipping libc6, it is already installed and upgrade is not set.
Skipping libcurl4, it is already installed and upgrade is not set.
libcurl4 set to manually installed.
Skipping libgcc-s1, it is already installed and upgrade is not set.
Skipping libldap-2.5-0, it is already installed and upgrade is not set.
libldap-2.5-0 set to manually installed.
Skipping libsqlite3-0, it is already installed and upgrade is not set.
libsqlite3-0 set to manually installed.
Skipping libstdc++6, it is already installed and upgrade is not set.
The following additional packages will be installed:
  libaio1
The following NEW packages will be installed:
  libaio-dev libaio1
0 upgraded, 2 newly installed, 0 to remove and 85 not upgraded.
Need to get 28.4 kB of archives.
After this operation, 110 kB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu jammy/main amd64 libaio1 amd64 0.3.112-13build1 [7176 B]
Get:2 http://archive.ubuntu.com/ubuntu jammy/main amd64 libaio-dev amd64 0.3.112-13build1 [21.2 kB]
debconf: delaying package configuration, since apt-utils is not installed
Fetched 28.4 kB in 0s (145 kB/s)
Selecting previously unselected package libaio1:amd64.
(Reading database ... 
(Reading database ... 100%
(Reading database ... 26659 files and directories currently installed.)
Preparing to unpack .../libaio1_0.3.112-13build1_amd64.deb ...
Unpacking libaio1:amd64 (0.3.112-13build1) ...
Selecting previously unselected package libaio-dev:amd64.
Preparing to unpack .../libaio-dev_0.3.112-13build1_amd64.deb ...
Unpacking libaio-dev:amd64 (0.3.112-13build1) ...
Setting up libaio1:amd64 (0.3.112-13build1) ...
Setting up libaio-dev:amd64 (0.3.112-13build1) ...
Processing triggers for libc-bin (2.35-0ubuntu3.8) ...
::endgroup::
✓ libaio-dev Added libaio-dev
✓ libc6 Added libc6
✓ libcurl4 Added libcurl4
✓ libgcc-s1 Added libgcc-s1
✓ libicu70 Added libicu70
✓ libldap-2.5-0 Added libldap-2.5-0
✓ libonig5 Added libonig5
✓ libsqlite3-0 Added libsqlite3-0
✓ libstdc++6 Added libstdc++6
[command]/usr/bin/tar --posix -cf cache.tzst --exclude cache.tzst -P -C /workspace/TEST/testing --files-from manifest.txt --use-compress-program zstdmt
Cache Size: ~0 MB (33367 B)
Cache saved successfully
```
+ Cache php extensions
```bash
Cache not found for input keys: Linux-jammy-x86_64-8.2-f936a3374dc8958811db54a2075a172da9af75d47ae768c25979724418bd9d88-20240716, Linux-jammy-x86_64-8.2-f936a3374dc8958811db54a2075a172da9af75d47ae768c25979724418bd9d88-20240716
```

**Additional context**
In this workflow, caching is already successfully used elsewhere (php-cs-fixer and composer), so I can rule out any issues with the caching functionality itself.
