### ISSUE TITLE
Missing packages for serval extensions

### ISSUE THREAD

**Issue by B0bbyD0llar** [shivammathur/cache-extensions#46]
**Describe the bug**

**Version**
- [X] I have checked releases and the bug exists in the latest patch version of `v1`.

**Runners**

- [ ] GitHub Hosted
- [X] Self Hosted

**Operating systems**
ubuntu-latest (Ubuntu 2404)

**PHP versions**
8.2

**To Reproduce**
```
    env:
      extensions: apcu, calendar, ctype, curl, ds, dom, fileinfo, filter, gd, iconv, imap, intl, json, ldap, mbstring, mysqlnd, pdo, pdo_mysql, pdo_sqlite, redis, session, simplexml, tokenizer, xml, xmlreader, xmlwriter, zip, zlib
      key: "cache-v6"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4.2.2"
      - name: "Setup php extensions cache environment"
        id: extcache
        uses: "shivammathur/cache-extensions@1.11.1"
        with:
          php-version: "${{ matrix.php-version }}"
          extensions: "${{ env.extensions }}"
          key: "${{ env.key }}"
      - name: "Cache php extensions"
        uses: "actions/cache@v4.1.2"
        with:
          path: "${{ steps.extcache.outputs.dir }}"
          key: "${{ steps.extcache.outputs.key }}"
          restore-keys: "${{ steps.extcache.outputs.key }}
```

**Expected behavior**
Cache all selected extensions

**Screenshots/Logs**
```
[command]/usr/bin/bash /run/act/actions/a4b689274cdadbd8b09084a274a674cb98a23347f69380f3fc6befa4369e5bac/src/scripts/cache.sh data apcu, calendar, ctype, curl, ds, dom, fileinfo, filter, gd, iconv, imap, intl, json, ldap, mbstring, mysqlnd, pdo, pdo_mysql, pdo_sqlite, redis, session, simplexml, tokenizer, xml, xmlreader, xmlwriter, zip, zlib 8.2 cache-v6
[command]/usr/bin/bash /run/act/actions/a4b68974cdadbd8b09084a274a674cb98a23347f69380f3fc6befa4369e5bac/src/scripts/cache.sh dependencies apcu, calendar, ctype, curl, ds, dom, fileinfo, filter, gd, iconv, imap, intl, json, ldap, mbstring, mysqlnd, pdo, pdo_mysql, pdo_sqlite, redis, session, simplexml, tokenizer, xml, xmlreader, xmlwriter, zip, zlib 8.2
==> Setup libraries
::group::Logs to set up required libraries
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package libaio-dev
E: Unable to locate package libc-client2007e
E: Unable to locate package libgd
E: Unable to locate package libxmlrpc-epi0
E: Unable to locate package libzip
Get:1 https://packages.microsoft.com/ubuntu/22.04/prod jammy InRelease [332 B]
Get:2 https://ppa.launchpadcontent.net/git-core/ppa/ubuntu jammy InRelease [24.6 kB]
```

**Additional context**
