### ISSUE TITLE
Config to disable workflow and job ids in the cache key

### ISSUE THREAD

**Issue by daadu** [shivammathur/cache-extensions#51]
**Describe the feature**
Currently the cache key is made with (along with other data) workflow+job id. This ensures that the seperate cache is maintained for each workflow+job combination.

However this might not be desirable, if you want to re-use the cache across all workflow. In my project, I setup-php with same extensions in all workflows (analyze, test-unit, test-feature...), sharing the cache across the workflow is desirable for such setup.

**Version**
- [x] I have checked releases and the feature is missing in the latest patch version of `v1`.

**Describe alternatives**
A partial work-around is to use static cache key (defined by the user) -- something like:

```yaml
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      php-version: "8.3"
      php-extensions: mbstring, intl, grpc, rdkafka

    steps:
      - uses: actions/checkout@v4

      - name: Setup php-extensions cache environment
        id: extcache
        uses: shivammathur/cache-extensions@v1
        with:
          php-version: ${{ env.php-version }}
          extensions: ${{ env.php-extensions }}
          key: any # <-- doesn't matter as we override it below

      - name: Cache php-extensions
        uses: actions/cache@v4
        with:
          path: ${{ steps.extcache.outputs.dir }}
          key:  ${{ runner.os }}-phpext-${{ env.php-version }}-${{ env.php-extensions }}
          restore-keys:  ${{ runner.os }}-phpext-${{ env.php-version }}
```

However, the issue with this is that, the cache would be used even if the php version is bumped, for eg from 8.3.19 --> 8.3.20.

**Therefore a proper solution would be to add an action-config (let's say `enable-cross-workflow` -- defaults to `false`) -- if this flag is enabled, then the workflow+job id is not used in "making the key"**

**Are you willing to submit a PR?**
Yes, if the solution is green-lighted.
