### ISSUE TITLE
Does this action work on ubicloud runners?

### ISSUE THREAD

**Issue by dev-anthonyrae** [shivammathur/cache-extensions#53]
Hi there, 
I've added the action to my github action, but it doesn't look like there is any performance gain or use of the cache when using ubicloud runners. When I tested with github runners, it worked as expected.

![Image](https://github.com/user-attachments/assets/165cb886-a1bf-4426-9eef-43418ecd9fa4)
![Image](https://github.com/user-attachments/assets/e20c07a5-ca29-4064-af5b-6439094e19f5)
![Image](https://github.com/user-attachments/assets/97339b3e-607e-4ad6-9ff6-35ac88ddcb8d)

```
steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for comparing changes

      - name: Setup cache environment
        id: extcache
        uses: shivammathur/cache-extensions@v1
        with:
          php-version: ${{ env.PHP_VERSION }}
          extensions: ${{ env.PHP_EXTENSIONS }}
          key: extension-cache-v1
        env:
          RUNNER: self-hosted

      - name: Cache extensions
        uses: ubicloud/cache@v4
        with:
          path: ${{ steps.extcache.outputs.dir }}
          key: ${{ steps.extcache.outputs.key }}
          restore-keys: ${{ steps.extcache.outputs.key }}
        env:
          RUNNER: self-hosted

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.PHP_VERSION }}
          extensions: ${{ env.PHP_EXTENSIONS }}
          coverage: none
          tools: composer:v2
          cache-version: 1
          cache-key: ${{ steps.extcache.outputs.key }}
        env:
          RUNNER: self-hosted
```
